### ISSUE TITLE
issue 1260577 running on the version of d8?

### ISSUE THREAD

**Issue by avboy1337** [vngkv123/aSiagaming#4]
sorry to bother you bro , the maps and other constants are so depended to the version of d8 , so could you please tell the version of d8?

**Comment by vngkv123** [comment]
Oh sorry for late, i worked on "63dc736d6bc69cf8849cc8588c6a0155954263db".

**Comment by avboy1337** [comment]
> 63dc736d6bc69cf8849cc8588c6a0155954263db

thanks bro , i think this hash is good enough!
